const demoCompanies = ['中招工业发展（北京）有限公司', '华北建设集团有限公司', '远东科技发展有限公司', '新城城市建设有限公司', '中原设备采购有限公司', '东岳工程服务有限公司', '天衡供应链有限公司', '启明信息技术有限公司'];
const demoSites = ['信用中国 · 严重失信主体名单', '信用中国 · 重大税收违法失信主体', '中国执行信息公开网 · 失信被执行人'];
const state = { view:'overview', browserVisible:true, paused:false, running:true, progress:62, companyIndex:5, taskName:'投标企业标前核查 · 8 家企业', mode:'visible', companies:demoCompanies, selectedSites:demoSites, tasks:[{name:'投标企业标前核查 · 8 家企业', time:'今天 09:42', status:'运行中', meta:'8 家企业 · 24 个核查项', progress:'62%'}] };
const $ = (id) => document.getElementById(id);
const siteChecks = () => [...document.querySelectorAll('.site-check input')];

function showView(view) {
  state.view = view;
  document.querySelectorAll('.view').forEach((el) => el.classList.remove('active-view'));
  const target = $(`${view}-view`);
  if (target) target.classList.add('active-view');
  document.querySelectorAll('.nav-item').forEach((el) => el.classList.toggle('active', el.dataset.view === view));
  const labels = { overview:'总览', history:'任务记录', sites:'站点适配', settings:'设置', create:'新建任务' };
  $('crumb').textContent = labels[view] || '总览';
  $('page-title').textContent = view === 'overview' ? '早上好，准备开始核查？' : (view === 'history' ? '所有任务，都在这里' : labels[view]);
  if (view === 'history') renderHistory();
}
function toast(message) { const el = $('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => el.classList.remove('show'), 2600); }
function openModal() { $('task-modal').classList.add('open'); $('task-modal').setAttribute('aria-hidden','false'); $('company-input').focus(); }
function closeModal() { $('task-modal').classList.remove('open'); $('task-modal').setAttribute('aria-hidden','true'); }
function updateCount() { const count = $('company-input').value.split(/\r?\n|,|，/).map(s=>s.trim()).filter(Boolean).length; $('input-count').textContent = `${count} 家`; }
function updateSiteCount() { const count = siteChecks().filter(i=>i.checked).length; $('selected-site-count').textContent = `${count}`; document.querySelectorAll('.site-check').forEach(label => label.classList.toggle('checked', label.querySelector('input').checked)); }
function syncBrowserBounds() { if (!window.electronAPI || !state.browserVisible) return; const target = $('browser-page'); if (!target) return; const rect = target.getBoundingClientRect(); window.electronAPI.setBrowserBounds({ x:rect.left, y:rect.top, width:rect.width, height:rect.height }); }
function updateBrowserMode() { const preview = $('browser-preview'); const hidden = $('browser-hidden-state'); preview.style.display = state.browserVisible ? 'block' : 'none'; hidden.style.display = state.browserVisible ? 'none' : 'flex'; $('toggle-browser-label').textContent = state.browserVisible ? '隐藏浏览器' : '显示浏览器'; if (state.browserVisible) requestAnimationFrame(syncBrowserBounds); }
function updateTaskUI() { $('progress-percent').textContent = `${state.progress}%`; $('progress-fill').style.width = `${state.progress}%`; $('progress-detail').textContent = `第 ${Math.min(state.companyIndex, state.companies.length)} 家 / 共 ${state.companies.length} 家 · 当前：${state.selectedSites[(state.companyIndex + 1) % state.selectedSites.length] || '信用中国'}`; $('active-task-name').textContent = state.taskName; $('active-task-status').textContent = state.paused ? '已暂停' : (state.running ? '运行中' : '已完成'); $('pause-label').textContent = state.paused ? '继续任务' : '暂停任务'; $('browser-company').textContent = state.companies[Math.min(state.companyIndex - 1, state.companies.length - 1)] || demoCompanies[0]; $('browser-result').textContent = state.paused ? '等待人工处理...' : (state.running ? '正在等待结果加载...' : '查询完成，截图已保存'); }
function startSimulation() { clearInterval(window.__runner); window.__runner = setInterval(() => { if (!state.running || state.paused) return; state.progress += 4; if (state.progress >= 100) { state.progress = 100; state.running = false; state.companyIndex = state.companies.length; clearInterval(window.__runner); toast('任务已完成，截图目录和 Excel 报告已生成'); } else if (state.progress % 12 === 0) state.companyIndex = Math.min(state.companies.length, state.companyIndex + 1); updateTaskUI(); }, 1600); }
function renderHistory() { const rows = state.tasks.map(t => `<div class="history-row"><div><strong>${t.name}</strong><small>${t.time} · ${t.meta}</small></div><div class="history-status ${t.status === '部分完成' ? 'warn' : 'done'}">${t.status}</div><div>${t.progress || '100%'}</div><div><button class="link-button">查看详情 →</button></div></div>`).join(''); $('history-table').innerHTML = `<div class="history-row header"><div>任务名称</div><div>状态</div><div>进度</div><div>操作</div></div>${rows}`; }
async function startNewTask() { const names = $('company-input').value.split(/\r?\n|,|，/).map(s=>s.trim()).filter(Boolean); const selected = siteChecks().filter(i=>i.checked).map(i=>i.dataset.site); if (!names.length) { toast('请先输入或导入至少一家企业'); return; } if (!selected.length) { toast('请至少选择一个核查项'); return; } state.companies = [...new Set(names)]; state.selectedSites = selected; state.taskName = `企业资质核查 · ${state.companies.length} 家企业`; state.progress = 3; state.companyIndex = 1; state.running = true; state.paused = false; state.browserVisible = document.querySelector('.mode-option.active')?.dataset.mode !== 'hidden'; state.tasks.unshift({ name:state.taskName, time:'刚刚', status:'运行中', meta:`${state.companies.length} 家企业 · ${selected.length * state.companies.length} 个核查项`, progress:'3%' }); closeModal(); showView('overview'); updateBrowserMode(); updateTaskUI(); if (window.electronAPI) { const response = await window.electronAPI.startTask({ companies:state.companies, sites:selected, outputFolder:null }); if (!response?.ok) toast(response?.message || '任务启动失败'); else toast('真实查询任务已启动'); } else { startSimulation(); toast('演示任务已启动'); } }
document.querySelectorAll('.nav-item').forEach(btn => btn.addEventListener('click', () => btn.dataset.view === 'create' ? openModal() : showView(btn.dataset.view)));
['new-task-button','history-new-task'].forEach(id => $(id).addEventListener('click', openModal));
['view-history','view-history-2'].forEach(id => $(id).addEventListener('click', () => showView('history')));
$('close-modal').addEventListener('click', closeModal); $('task-modal').addEventListener('click', (e) => { if (e.target === $('task-modal')) closeModal(); });
$('company-input').addEventListener('input', updateCount); $('use-demo-data').addEventListener('click', () => { $('company-input').value = demoCompanies.join('\n'); updateCount(); toast('已载入 8 家示例企业'); });
$('company-file').addEventListener('change', (e) => { const file = e.target.files[0]; if (!file) return; if (/\.xlsx?$|\.xls$/i.test(file.name) && window.electronAPI?.parseExcel) { const reader = new FileReader(); reader.onload = async () => { try { const names = await window.electronAPI.parseExcel(reader.result); $('company-input').value = names.join('\n'); $('file-hint').textContent = `${file.name} 已解析，读取 ${names.length} 家企业`; updateCount(); } catch (error) { toast(`Excel 解析失败：${error.message}`); } }; reader.readAsArrayBuffer(file); } else if (/\.txt$|\.csv$/i.test(file.name)) { $('file-hint').textContent = `${file.name} 已载入`; const reader = new FileReader(); reader.onload = () => { $('company-input').value = String(reader.result).replace(/\r/g,'').split(/\n|,/).map(s=>s.trim()).filter(Boolean).join('\n'); updateCount(); }; reader.readAsText(file, 'utf-8'); } else { toast('请选择 Excel、CSV 或 TXT 文件'); } });
siteChecks().forEach(input => input.addEventListener('change', updateSiteCount)); document.querySelectorAll('.mode-option').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.mode-option').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); state.mode = btn.dataset.mode; }));
$('start-task').addEventListener('click', startNewTask);
$('toggle-browser').addEventListener('click', () => { if (window.electronAPI) window.electronAPI.toggleBrowser(!state.browserVisible); }); $('show-browser-button').addEventListener('click', () => { if (window.electronAPI) window.electronAPI.toggleBrowser(true); }); $('pause-task').addEventListener('click', async () => { state.paused = !state.paused; if (window.electronAPI) { await (state.paused ? window.electronAPI.pauseTask() : window.electronAPI.resumeTask()); } updateTaskUI(); toast(state.paused ? '任务已暂停' : '任务继续执行'); }); $('open-folder').addEventListener('click', () => window.electronAPI ? window.electronAPI.openFolder() : toast('演示模式：任务完成后将在此处打开截图目录'));
if (window.electronAPI) window.electronAPI.onTaskUpdate((update) => { if (typeof update.progress === 'number') state.progress = update.progress; if (typeof update.browserVisible === 'boolean') { state.browserVisible = update.browserVisible; updateBrowserMode(); } if (update.index) state.companyIndex = update.index; if (update.total) state.companies = state.companies.length ? state.companies : demoCompanies; if (update.company) $('browser-company').textContent = update.company; if (update.status === 'paused' || update.status === 'manual') state.paused = true; if (update.status === 'running' || update.status === 'success') state.paused = false; if (update.status === 'completed' || update.status === 'stopped') state.running = false; if (update.message) $('browser-result').textContent = update.message; if (update.site) $('browser-site').textContent = update.site; if (update.folder) state.taskFolder = update.folder; updateTaskUI(); if (update.status === 'manual') toast('需要人工处理：请在浏览器中完成验证后点击继续'); if (update.status === 'completed') toast(`任务已完成，报告已生成：${update.reportPath || update.folder}`); if (update.status === 'failed') toast(`执行失败：${update.message}`); });
window.addEventListener('resize', syncBrowserBounds); window.addEventListener('scroll', syncBrowserBounds, true);
updateCount(); updateSiteCount(); updateBrowserMode(); updateTaskUI(); if (!window.electronAPI) startSimulation();
