#!/usr/bin/env node
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
const { PRODUCT_ID, LICENSE_EXTENSION, canonicalLicensePayload, normalizePayload } = require('../electron/license');

function args(values) {
  const output = { _: [] };
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (!value.startsWith('--')) { output._.push(value); continue; }
    const key = value.slice(2);
    output[key] = values[index + 1] && !values[index + 1].startsWith('--') ? values[++index] : true;
  }
  return output;
}

function required(options, name) {
  if (!options[name] || options[name] === true) throw new Error(`缺少 --${name}`);
  return String(options[name]);
}

function isDate(value) { return /^\d{4}-\d{2}-\d{2}$/.test(value); }

async function createKeys(options) {
  const privatePath = path.resolve(required(options, 'private-key'));
  const publicModulePath = path.resolve(options['public-module'] || path.join(__dirname, '..', 'electron', 'license-public-key.js'));
  const pair = crypto.generateKeyPairSync('ed25519');
  const privateKey = pair.privateKey.export({ type: 'pkcs8', format: 'pem' });
  const publicKey = pair.publicKey.export({ type: 'spki', format: 'pem' });
  await fs.mkdir(path.dirname(privatePath), { recursive: true });
  await fs.writeFile(privatePath, privateKey, { mode: 0o600 });
  await fs.mkdir(path.dirname(publicModulePath), { recursive: true });
  await fs.writeFile(publicModulePath, `// Generated by tools/license-cli.js. This public key is included in the application.\nmodule.exports = {\n  publicKey: ${JSON.stringify(publicKey)}\n};\n`, 'utf8');
  process.stdout.write(`私钥：${privatePath}\n公钥模块：${publicModulePath}\n`);
}

async function issue(options) {
  const privateKey = await fs.readFile(path.resolve(required(options, 'private-key')), 'utf8');
  const expiresAt = required(options, 'expires');
  if (!isDate(expiresAt)) throw new Error('--expires 必须为 YYYY-MM-DD，例如 2027-08-21');
  const machineCode = required(options, 'machine-code').trim().toUpperCase();
  if (!/^JH1(?:-[A-F0-9]{8}){5}$/.test(machineCode)) throw new Error('--machine-code 格式无效');
  const issuedTo = required(options, 'customer').trim();
  const issuedAt = options['issued-at'] ? String(options['issued-at']) : new Date().toISOString().slice(0, 10);
  if (!isDate(issuedAt)) throw new Error('--issued-at 必须为 YYYY-MM-DD');
  const payload = normalizePayload({
    product: PRODUCT_ID,
    licenseId: options['license-id'] || `JH-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,
    issuedTo,
    machineCode,
    issuedAt,
    expiresAt,
    features: ['task-execution']
  });
  const signature = crypto.sign(null, Buffer.from(canonicalLicensePayload(payload), 'utf8'), privateKey).toString('base64');
  const license = { ...payload, signature };
  const output = path.resolve(options.output || `${payload.licenseId}${LICENSE_EXTENSION}`);
  await fs.writeFile(output, `${JSON.stringify(license, null, 2)}\n`, 'utf8');
  process.stdout.write(`已签发：${output}\n授权编号：${payload.licenseId}\n授权对象：${payload.issuedTo}\n到期日：${payload.expiresAt}\n`);
}

async function main() {
  const [command, ...rest] = process.argv.slice(2);
  const options = args(rest);
  if (command === 'create-keys') return createKeys(options);
  if (command === 'issue') return issue(options);
  throw new Error('用法：\n  node tools/license-cli.js create-keys --private-key <私钥路径>\n  node tools/license-cli.js issue --private-key <私钥路径> --machine-code <授权申请码> --customer <单位名称> --expires YYYY-MM-DD --output <授权文件路径>');
}

main().catch((error) => { process.stderr.write(`签发失败：${error.message}\n`); process.exitCode = 1; });
